### ISSUE TITLE
[HZN-102] Improve fitting algorithm for T1 relaxometry

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#101]
Transferred by @LaurenceJackson on Mar 23, 2021, 16:50

:::Issue recreated from Jira issue [HZN-102](https://gsttmri.atlassian.net/browse/HZN-102):::

T1 relaxometry images are typically acquired as magnitude images despite really being signed inversion recovery images. The current algorithm fits an the (unsigned) data to the absolute value of the decay equation. On one occasion (see image) this has led to suboptimal fitting where the first data point is fitted as a negative point when a positive point would be better. The discontinuity in the derivative of the function means the solver gets trapped in a local minima.

!image-20210323-155948.png|width=521,height=188!

Rather than fitting to a magnitude of the recovery equation, we can fit to the signed equation with all data points positive, then again with the first negative, and again with the first two points negative, etc. The fit with the lowest MSE would be selected.

**Comment by laurencejackson** [comment]
Transferred by @LaurenceJackson on Mar 23, 2021, 17:07

![image-20210323-155948](https://my-gitlab-bucket.s3.amazonaws.com/393326940/93709098cb5288cbe40624be29ca852f.png)

**Comment by tomaroberts** [comment]
Closing because relaxometry Task not widely used and dev work not insignificant – happy to reopen in future.
