### ISSUE TITLE
[HZN-103] SNR parametric map

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#102]
Transferred by @LaurenceJackson on Mar 23, 2021, 17:08

:::Issue recreated from Jira issue [HZN-103](https://gsttmri.atlassian.net/browse/HZN-103):::

Merge and develop PW's existing code for producing SNR parametric maps.

**Comment by tomaroberts** [comment]
Partially completed, at least. Merge conflicts.

**Comment by tomaroberts** [comment]
Closed by PR #113
