### ISSUE TITLE
[HZN-104] Tests failing to run on develop branch (26/03/2020)

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#103]
Transferred by @LaurenceJackson on Mar 26, 2021, 13:57

:::Issue recreated from Jira issue [HZN-104](https://gsttmri.atlassian.net/browse/HZN-104):::

Error received below when trying to run ghosting tests on origin/develop branch on 26/03/2020. Also tried to run SNR, same error received. Appears to be related to recent changes to relaxometry code.

(hazen-venv) (base) Janes-MacBook:cavell_2021 Ansell$ hazen ghosting nsa1
Traceback (most recent call last):
  File "/Users/Ansell/hazen-venv/bin/hazen", line 11, in <module>
    load_entry_point('hazen', 'console_scripts', 'hazen')()
  File "/Users/Ansell/hazen_code/hazenlib/__init__.py", line 326, in main
    relaxometry_cli_args_used = [arg for arg in relaxometry_cli_args if arguments[arg]]
  File "/Users/Ansell/hazen_code/hazenlib/__init__.py", line 326, in <listcomp>
    relaxometry_cli_args_used = [arg for arg in relaxometry_cli_args if arguments[arg]]
KeyError: '--verbose'

**Comment by tomaroberts** [comment]
Resolved by #116
