### ISSUE TITLE
[HZN-107] Ignore non-DICOM files in working directory

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#106]
Transferred by @LaurenceJackson on Jun 17, 2021, 15:35

:::Issue recreated from Jira issue [HZN-107](https://gsttmri.atlassian.net/browse/HZN-107):::

Hazen should ignore non-DICOM files in a directory rather than crash.

**Comment by hshuaib90** [comment]
Closed with #132
