### ISSUE TITLE
[HZN-108] Stop hazen output splitting dict value stings which contain a space

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#107]
Transferred by @LaurenceJackson on Jun 17, 2021, 15:43

:::Issue recreated from Jira issue [HZN-108](https://gsttmri.atlassian.net/browse/HZN-108):::

Current __init__.py uses pprint to display results dict. If a value in results is a string containing a space, the string is split and displayed on multiple lines.

E.g. 
>>> print(results) # ugly, limited formatting but strings kept intact.
{'snr_map_detailed_SNR SE Ax Head TE30_206_1_20482196': 'SNR SE Ax Head TE30_206_1_20482196_snr_map_detailed.png', 'snr_map_SNR SE Ax Head TE30_206_1_20482196': 'SNR SE Ax Head TE30_206_1_20482196_snr_map.png', 'snr_map_snr_SNR SE Ax H
ead TE30_206_1_20482196': 158.4697884657242}

>>> pprint(results)  # Display when command run from terminal e.g. "hazen snr_map ."
{   'snr_map_SNR SE Ax Head TE30_206_1_20482196': 'SNR '
                                                  'SE '
                                                  'Ax '
                                                  'Head '
                                                  'TE30_206_1_20482196_snr_map.png',
    'snr_map_detailed_SNR SE Ax Head TE30_206_1_20482196': 'SNR '
                                                           'SE '
                                                           'Ax '
                                                           'Head '
                                                           'TE30_206_1_20482196_snr_map_detailed.png',
    'snr_map_snr_SNR SE Ax Head TE30_206_1_20482196': 158.4697884657242}

**Comment by sophie22** [comment]
I am unable to recreate this behaviour. Output from current snr_map task looks as expected:
<img width="1039" alt="Screenshot 2023-07-05 at 11 26 20" src="https://github.com/GSTT-CSC/hazen/assets/15593138/84369424-b853-4770-8ec1-e6b126796132">

**Comment by tomaroberts** [comment]
Thanks @sophie22 – I will close. I suspect this was actually solved a while ago then.
