### ISSUE TITLE
SNR failing on Sola and Vida scanners

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#108]
The head SNR in the sagittal plane is failing consistently across Sola and Vida.  Perhaps bright areas on the images close to the coil elements?

<img width="566" alt="image" src="https://user-images.githubusercontent.com/33687657/128342065-fea7129a-d4e0-4347-aef6-b4e1c4c772d7.png">

Example image data stored under `Quality/Hazen_Issues/`
Raised on behalf of David Price.

**Comment by tomaroberts** [comment]
Resolved by #137
