### ISSUE TITLE
Ghosting measurements on Philips Ingenia 1.5T

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#109]
Ghosting not working- according to position of max ghosting not in rectangular box as desired.  Perhaps something in Philips header?

![image](https://user-images.githubusercontent.com/33687657/128342559-62d99832-8aa6-4416-a425-45bbb09bc325.png)

Example image data stored under `quality/Hazen_Issues/`
Raised on behalf of David Price.

**Comment by hshuaib90** [comment]
David Price: Fails on GE scanner too

**Comment by tomaroberts** [comment]
Fixed by PR #185
