### ISSUE TITLE
Transition usage to Docker version

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#117]
A docker verison of Hazen exists but is not fully documented or utilised. This is more important now since there is no simple way to set up python3.6 on M1 macs, using docker gets around this issue.

Tasks I can think of, feel free to suggest more if there is more we can do with this.
- [x] update documentation to cover installation and usage of docker version
- [x] update CI/CD pipelines to push a new tagged image to dockerhub when master branch is updated (this is addressed in #119

**Comment by hshuaib90** [comment]
Hi @laurencejackson - are you able to do this documentation so we can merge this?

**Comment by laurencejackson** [comment]
Yes, I'll do that now

**Comment by hshuaib90** [comment]
Closed with #136
