### ISSUE TITLE
MRS email pdf attachment not showing up in outlook mac

### ISSUE THREAD

**Issue by MariaICL** [GSTT-CSC/hazen#139]
MRS email results (the pdf attachments) are currently not visible to mac outlook users. This has been going on for at least a few months (I do not have a mac, so not sure since which update of dicomserver).

Would anyone know how to fix this? (MRS email pdf attachments are visible to Windows outlook users).

I attach an screenshot of the email's appearance in mac.

Many thanks,

Maria.
![image](https://user-images.githubusercontent.com/18559344/140784761-a46fd8c6-bde4-4d3e-be3e-6f10105a91a1.png)

**Comment by laurencejackson** [comment]
Hi @MariaICL, just seen this in here! This is not a hazen issue, could you re-raise this on the dicomserver repository?

https://bitbucket.org/gsttmri/dicomserver/issues?status=new&status=open
