### ISSUE TITLE
Improve --report option functionality

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/hazen#156]
Currently, it's not entirely clear which functions provide additional output when using the `--report` option. Furthermore, the output images are saved in the directory where the hazen command was run. This can be confusing particularly if the user is not used to CLI interactivity.

Suggestions for improvements:
- Provide some feedback on where files are saved, if they are indeed saved
- Allow user to specify file save path

- default save path?:
    - the same as input path, i.e.: the folder of DICOMs on which the function was performed
    - OR (slightly more complicated, but keeps the DICOM folders unchanged):
    - have hazen create a new directory called 'hazen_report' at the same directory level as the DICOM series folders, where output files can be saved?

**Comment by laurencejackson** [comment]
Just a thought - you'll need to bear in mind the docker implementation here. When running the docker image the current working directory is mounted into `/home/hazen_user/data` inside the container. So any save location will need to be at the level of cwd or below or it will be inaccessible to the container.

**Comment by hshuaib90** [comment]
I would prefer a 'documentation solution to this in the first instance. Every function should have a help menu associated with it, which explains what the module does and what the valid options are including e.g. --report.

**Comment by tomaroberts** [comment]
Partially addressed by https://github.com/GSTT-CSC/hazen/releases/tag/1.1.0

When using the `--report` option, hazen now outputs report results to a directory called `report`. Users can also specify a folder on their computer where they want the report results to be output.

**Comment by sophie22** [comment]
outstanding part: identify which tasks can generate a report?

**Comment by tomaroberts** [comment]
I think this issue is an old one and the main improvements (e.g. enabling report output location to be specified and displayed) have actually been resolved.

I would suggest we close this one and create a new one specifically to address the problem that users don't know which Tasks output reports, and which don't.

**Comment by sophie22** [comment]
All tasks converted to inherit from the HazenTask have the option to generate a report (which is one or more images), except for the relaxometry task which is to be refactored.
When `--report` is used, output images are stored in a folder `report/<task>/image` by default or an output folder can be specified using `--output <path>`
