### ISSUE TITLE
Use Ibn Al-Haytham's image instead of CSC logo

### ISSUE THREAD

**Issue by hshuaib90** [GSTT-CSC/hazen#158]
**Is your feature request related to a problem? Please describe.**
I think it would be more appropriate to have the image of Ibn Al-Haytham (who inspired the name Hazen) instead of the CSC logo. I think it would be better for community to development to not include CSC branding.

**Describe the solution you'd like**
Replace CSC logo with Ibn Al-Haytham's image in README.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by tomaroberts** [comment]
Completed in #143, commit: #3cadc1d
