### ISSUE TITLE
Add unit tests to test_ghosting

### ISSUE THREAD

**Issue by Lucrezia-Cester** [GSTT-CSC/hazen#162]
write test functions for ghosting script

**Comment by laurencejackson** [comment]
Hi Lu, which ghosting script do you mean? We already have a test_ghosting.py. Or is this issue related to increasing the test coverage? In which case we should link it to #134

**Comment by Lucrezia-Cester** [comment]
@laurencejackson yes it's test coverage related to #134. Tom and I are sharing the task of writing tests.

**Comment by jip23** [comment]
Could this be prioritised for 0.6.0?

**Comment by tomaroberts** [comment]
Closing as covered by #134
