### ISSUE TITLE
Fill in the hazen "about" section

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#172]
**Is your feature request related to a problem? Please describe.**
We should fill, in the about section with a short description and some relevant tags - see below for current hazen about. This will help us with search engine visibility.

![image](https://user-images.githubusercontent.com/33687657/145610334-d7808d55-d770-4f54-a7d4-9990d53ee58f.png)

**Describe the solution you'd like**
I did something similar for the MLOps page - below- it doesn't need to be much but this meant i could find the repo on google.
![image](https://user-images.githubusercontent.com/33687657/145610664-55484676-05f5-4ed7-a49f-640dc379172f.png)

**Describe alternatives you've considered**
leaving it empty?

**Comment by tomaroberts** [comment]
Partially done without needing PR:

![image](https://user-images.githubusercontent.com/15610752/147107905-252c3452-9475-4d6c-bd2a-455a01fefa83.png)

See also #194 for citation button which will close this issue.

**Comment by tomaroberts** [comment]
Closed by #194
