### ISSUE TITLE
Windows install fail: psycopg2-binary in requirements.txt

### ISSUE THREAD

**Issue by pcw24601** [GSTT-CSC/hazen#176]
**Describe the bug**
requirements.txt cannot be installed on clean Windows environment--psycopg2-binary causes failure

**To Reproduce**
1. Run `pip install -r requirements.txt` under Windows 10 in a  clean virtual environment.
2. Script halts with 

```
Error: pg_config executable not found.

  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:

      python setup.py build_ext --pg-config /path/to/pg_config build ...

  or with the pg_config option in 'setup.cfg'.

  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

  For further information please check the 'doc/src/install.rst' file (also at
  <http://initd.org/psycopg/docs/install.html>).
```

**Expected behavior**
All packages should install normally.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by tomaroberts** [comment]
Ugh. Thanks Paul, this package continues to be a thorn.

Can you attach a textfile of the full error output? Everything between the command you run and the end of the output. It might be long... Can investigate a bit more closely – might be a similar problem to one we've previously encountered.

**Comment by tomaroberts** [comment]
Actually, it looks like a PostgreSQL issue. Some links here to look at:

https://stackoverflow.com/questions/36846579/error-when-installing-psycopg2-on-windows-10
^^ Might be worth trying altering the `requirements.txt` from psycopg2-binary > psycopg2 and running `pip install -r requirements.txt`

Not Windows, but has some useful clues:
https://stackoverflow.com/questions/11618898/pg-config-executable-not-found

**Comment by pcw24601** [comment]
Hi @tomaroberts , thanks for the quick feedback. I tried changing to psycopg2 but the install still fails.

Dump of error message from original (binary) attempt.
[install_fail.txt](https://github.com/GSTT-CSC/hazen/files/7705130/install_fail.txt)

If I comment out the line everything works fine. Also, installing directly seems to work (although a later version):
```
> pip install psycopg2
Collecting psycopg2
  Downloading psycopg2-2.9.2-cp39-cp39-win_amd64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 2.2 MB/s
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.2
```

**Comment by hshuaib90** [comment]
The Postgresql backend is used for the hazen web app, so psycopg2 is not required to run hazen using the CLI. Might be worth considering splitting out the web app repo.

**Comment by tomaroberts** [comment]
@pcw24601 – are you running Windows 10 with powershell or WSL2 btw?

I've got a Windows PC at home, so I can try and recreate the issue on it as well.

**Comment by pcw24601** [comment]
I'm running Windows 10 with Powershell (I'm interested in WSL2 but know it would be something of a black hole that consumes a lot of time learning). I (try to) manage Python versions with `pyenv` and virtual environments with `python -m venv`, then code in Pycharm. I have a notes on how I set it up if they are useful for any other Windows user.

I've only used the CLI version of hazen (or written my own wrapper functions).

**Comment by tomaroberts** [comment]
@pcw24601 – as you're running the CLI version of hazen and are pretty comfortable with it, I suggest commenting out the `psycopg2-binary` package in the `requirements.txt` file, then re-running pip install. Hopefully that should work. As Haris says, that package is just for the web app.

**Comment by pcw24601** [comment]
Thanks, commenting out the line works.

**Comment by tomaroberts** [comment]
Hey @pcw24601 – I think this issue is no longer an issue for hazen CLI as we've removed a lot of the dependencies from this repo which were to do with the web-app. We're also now using PyPI for simpler installation.

Are you happy if I close this issue? Perhaps if you haven't installed for a while and want to test, try installing the latest hazen version and hopefully it will be fine.

**Comment by tomaroberts** [comment]
Closing as resolved with hazen-web-app repo
