### ISSUE TITLE
`-v` flag does not return hazen version

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#180]
**Describe the bug**
running hazen -v returns an error instead of the version number,  --version works as expected.

**To Reproduce**
run hazen -v or hazen-app -v

**Expected behavior**
the version number should be returned

**Screenshots**
![image](https://user-images.githubusercontent.com/33687657/146033727-aceee250-55fa-480c-93a7-f9bfca6f928a.png)

**Comment by laurencejackson** [comment]
Just to add here for reference - using the full `--version` flag successfully returns the version number, the issue is only with the shortened `-v` flag

**Comment by tomaroberts** [comment]
Removed `-v` option in https://github.com/GSTT-CSC/hazen/pull/292
