### ISSUE TITLE
README does not forward to documentation

### ISSUE THREAD

**Issue by tawilkinson** [GSTT-CSC/hazen#181]
**Describe the bug**
The README does not link to any documentation

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [README](https://github.com/GSTT-CSC/hazen)
2. Click on `Explore the docs »`
3. A 404 page at https://github.com/github_username/repo_name is returned

**Expected behaviour**
This would link to hosted documentation

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 96.0.4664.93

**Additional context**
N/A

**Comment by heyhaleema** [comment]
Fixed by #301.
