### ISSUE TITLE
[ACR1] ACR phantom – SNR function 

### ISSUE THREAD

**Issue by jip23** [GSTT-CSC/hazen#182]
**Is your feature request related to a problem? Please describe.**
SNR function is missing for ACR phantom 

Priority: high for ACR

**Comment by tomaroberts** [comment]
@YassineRMH – just to be sure, I think this feature is now in hazen and can be closed?

**Comment by YassineAzma** [comment]
@tomaroberts There is an existing SNR function for the MagNet phantom. I'll be starting work on adapting that to work for the ACR phantom soon.

**Comment by tomaroberts** [comment]
Ok, will leave this open then, thanks for clarification.

**Comment by YassineAzma** [comment]
This has been resolved in PR #309 .
