### ISSUE TITLE
[ACR2] ACR phantom – spatial resolution measurement using MTF 

### ISSUE THREAD

**Issue by elizaGSTT** [GSTT-CSC/hazen#183]
The outcome from using the imageJ plugin and the manual calculation, greatly underestimates the effective pixel size (it's a lot smaller than the actual pixel spacing) and it is also hard to compare it with the current hazen results for the magNET phantom. We therefore need to calculate the MTF using the slanted edge method using an ROI as in the screenshot, in slice #1 of the phantom- use only the ramp for the edge block not the spatial res insert. From there after, we keep the 50% MTF value and do the following calculation to find the effective pixel size = 1/ (50%MTF x 2).
Priority: High importance for ACR analysis (please prioritize along with SNR)

![image](https://user-images.githubusercontent.com/93722461/146213853-38061b27-0c2e-433f-b32a-2bf041d36981.png)

**Comment by YassineAzma** [comment]
#324 resolves this.
