### ISSUE TITLE
Uniformity measurement

### ISSUE THREAD

**Issue by elizaGSTT** [GSTT-CSC/hazen#187]
For the uniformity measurement, use slice 7 of the ACR_TRA_T1_NORMON series. Place a large circular ROI of area: 195- 205 cm2 in the phantom. Lower the window level until the area inside the ROI is white, and then raise the level until a 1 cm2 region of dark pixels develops inside the ROI (Region of lowest signal). Record this region of lowest signal.Then raise the level until a 1 cm2 region of white pixels remains inside the ROI (region of highest signal). Record region of highest signal. Calculate the percent integral uniformity: PIU = 100 x (1 – {(high – low)/(high + low)})

Priority: high for ACR

![image](https://user-images.githubusercontent.com/93722461/146513707-1f95819f-c952-45ed-b185-1995927fffbd.png)

**Comment by laurencejackson** [comment]
Hi @elizaGSTT, did you mean to close this issue? If yes, could you provide a closing statement so we know why it's no longer required? Or we can reopen it if the issue is not resolved.

**Comment by elizaGSTT** [comment]
I actually closed it cause I accidentally created a duplicate one as I thought the first time it wasn’t submitted correctly. Do you still need me to write that on github?

From: Laurence Jackson ***@***.***>
Date: Monday, 20 December 2021 at 10:14
To: GSTT-CSC/hazen ***@***.***>
Cc: Stamou Elizabeth ***@***.***>, Mention ***@***.***>
Subject: Re: [GSTT-CSC/hazen] Uniformity measurement (Issue #187)

Hi @elizaGSTT<https://scanmail.trustwave.com/?c=8248&d=9dfA4YU2N1bjyDeCWqxCAcStDRYo_VsRE2WhhgdtnQ&u=https%3a%2f%2fgithub%2ecom%2felizaGSTT>, did you mean to close this issue? If yes, could you provide a closing statement so we know why it's no longer required? Or we can reopen it if the issue is not resolved.

—
Reply to this email directly, view it on GitHub<https://scanmail.trustwave.com/?c=8248&d=9dfA4YU2N1bjyDeCWqxCAcStDRYo_VsREzHwggI9lg&u=https%3a%2f%2fgithub%2ecom%2fGSTT-CSC%2fhazen%2fissues%2f187%23issuecomment-997784484>, or unsubscribe<https://scanmail.trustwave.com/?c=8248&d=9dfA4YU2N1bjyDeCWqxCAcStDRYo_VsREzChgAxtlQ&u=https%3a%2f%2fgithub%2ecom%2fnotifications%2funsubscribe-auth%2fAWLBOXKYKPVOZDHEPAEODGTUR36XBANCNFSM5KIIL36A>.
Triage notifications on the go with GitHub Mobile for iOS<https://scanmail.trustwave.com/?c=8248&d=9dfA4YU2N1bjyDeCWqxCAcStDRYo_VsREz7x0ARsxw&u=https%3a%2f%2fapps%2eapple%2ecom%2fapp%2fapple-store%2fid1477376905%3fct%3dnotification-email%26mt%3d8%26pt%3d524675> or Android<https://scanmail.trustwave.com/?c=8248&d=9dfA4YU2N1bjyDeCWqxCAcStDRYo_VsREzTy1FBnlw&u=https%3a%2f%2fplay%2egoogle%2ecom%2fstore%2fapps%2fdetails%3fid%3dcom%2egithub%2eandroid%26referrer%3dutm%5fcampaign%253Dnotification-email%2526utm%5fmedium%253Demail%2526utm%5fsource%253Dgithub>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

*************************************************************************************

The information contained in this message and or attachments is intended only for the
person or entity to which it is addressed and may contain confidential and/or 
privileged material. Unless otherwise specified, the opinions expressed herein do not
necessarily represent those of Guy's and St Thomas' NHS Foundation Trust or 
any of its subsidiaries. The information contained in this e-mail may be subject to 
public disclosure under the Freedom of Information Act 2000. Unless the information 
is legally exempt from disclosure, the confidentiality of this e-mail and any replies
cannot be guaranteed.

Any review, retransmission,dissemination or other use of, or taking of any action in 
reliance upon, this information by persons or entities other than the intended
recipient is prohibited. If you received this in error, please contact the sender
and delete the material from any system and destroy any copies.

We make every effort to keep our network free from viruses. However, it is your
responsibility to ensure that this e-mail and any attachments are free of viruses as
we can take no responsibility for any computer virus which might be transferred by 
way of this e-mail.

*************************************************************************************
