### ISSUE TITLE
[ACR4] Uniformity measurement 

### ISSUE THREAD

**Issue by elizaGSTT** [GSTT-CSC/hazen#188]
For the uniformity measurement, use slice 7 of the ACR_TRA_T1_NORMON series. Place a large circular ROI of area: 195-205 cm2 in the phantom. Lower the window level until the area inside the ROI is white, and then raise the level until a 1 cm2 region of dark pixels develops inside the ROI (Region of lowest signal). 
Record this region of lowest signal.
Then raise the level until a 1 cm2 region of white pixels remains inside the ROI (region of highest signal). Record region of highest signal. Calculate the percent integral uniformity:
PIU = 100 x (1 – {(high – low)/(high + low)})

Priority: high for ACR

![image](https://user-images.githubusercontent.com/93722461/146513893-91eedc02-eb9f-4274-b6bf-b258b07bbfab.png)

**Comment by tomaroberts** [comment]
@YassineRMH – just to be sure, I think this feature is now in hazen and can be closed?

**Comment by YassineAzma** [comment]
@tomaroberts Yep. I've closed this issue.
