### ISSUE TITLE
[ACR5] Geometric accuracy 

### ISSUE THREAD

**Issue by elizaGSTT** [GSTT-CSC/hazen#189]
For the geometric accuracy - currently under slice width in hazen - use slice 1 and slice 5 of an ACR_TRA_T1_NORMOFF series. In slice 1, measure the diameter of the phantom: top-to-bottom and left-to-right and on slice 5 measure the diameter of the phantom in 4 directions: top-to-bottom, left-to-right, and both diagonals. The diameter is 190 mm and all lengths should be within ± 2 mm.  Beware that on top of the phantom due to a water bubble there will be a n extended dark area.

Priority: High for ACR 

![image](https://user-images.githubusercontent.com/93722461/146515895-16ef0d2b-817c-428a-8cdf-1526635c8217.png)

**Comment by YassineAzma** [comment]
This has been resolved in PR #312 .
