### ISSUE TITLE
Bugfix: remove references to sites where data originated from

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/hazen#201]
hazen refers to places like EastKent and other sites in the code/test data. We should remove any of these references.

**Comment by pcw24601** [comment]
This data is likely still recorded in the DICOM header of the files. Ideally this should be anonymised too.

I've adapted [dicognito](https://github.com/blairconrad/dicognito) on the files I uploaded. For completeness, you can [get your own DICOM UID prefix](https://www.medicalconnections.co.uk/FreeUID/) to use so files remain DICOM compliant.
