### ISSUE TITLE
Split hazenlib and hazen app into seperate repositories

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#202]
**Is your feature request related to a problem? Please describe.**
The hazen repository is confusing in its current state, an inexperienced new user who expects to find some code for MRI QA has to look through a lot of additional files to find the functional parts. 

I think there is some reluctance for new users from a non-computing background to contribute to hazen given the apparent complexity of the project due to all the web app components. 

As developers maintaining and developing a webapp and the 

**Describe the solution you'd like**
The code should be split into two separate repositories

1. hazen: The hazenlib libraries 
2. hazen-webapp: the webapp and backend

The hazen repo with the hazenlib code can then be shared through PyPI and becomes a requirement for the hazen-webapp repo.

Benefits:
- Makes the hazen library more accessible and flexible for use with other internal/external projects
- starting a separate hazen-webapp repo at this point will allow us to isolate the development from the hazen library
- Removes a lot of the apparent complexity of the hazen library. Someone who just wants to understand how a metric is measured can more easily find the relevant code
- Security issues are more frequent with web code, isolating this will make resolving these more streamlined
- webapp and library can update separetely
- Physicists are likely more comfortable contributing to the hazen library but are possibly put off by the additional requirements of web development that currently comes with it. 

Cons:
- Additional repository can be confusing, but unlikely to cause any problems since majority of hazen users will access through webapp and won't need access to source code.

**Describe alternatives you've considered**
Keeping the repositories combined, also an option but I think the benefits are worthwhile.

Please provide thoughts and additional benefits/cons you can think of below.

**Comment by laurencejackson** [comment]
Sorry to assign everyone to this issue, just doing it to make sure everyone sees it so can offer their input since this is discussing potentially making a big change.

**Comment by tomaroberts** [comment]
I think it's a sensible idea – can just make hazenlib a submodule or similar in the hazen-app repo. Then they can be updated independently.

How about the GitHub Actions? Will those be straightforward to amend and split between the two?

**Comment by laurencejackson** [comment]
The GitHub actions as they are now are set up for testing hazenlib only. I don't think we have any tests for the webapp at the moment, so we will need new ones for the hazen-app repository.

I feel that publishing hazen on PyPI with it listed as a requirement in the app repo and having an action to automatically update the PyPI version with each new release would work better than git submodules. That makes it a bit easier for other developers to use some of the hazenlib functions if they need them, and there's no need to remember to run the git submodule commands when cloning. But what do you think?

**Comment by tomaroberts** [comment]
Oh yeah, agree, didn't quite take that bit in fully. PyPI would be great definitely.

**Comment by tomaroberts** [comment]
Resolved. We now have the hazen repo you are looking at right now and the [hazen-web-app](https://github.com/GSTT-CSC/hazen-web-app) repo.
