### ISSUE TITLE
Release under an appropriate license--currently no use is permitted!

### ISSUE THREAD

**Issue by pcw24601** [GSTT-CSC/hazen#225]
**Is your feature request related to a problem? Please describe.**
The current licence file states users cannot legally use the Hazen software. This could inhibit software uptake, lacks clarity for developers, and may make it difficult to manage the codebase as the number of contributors (=copyright holders) grows.

**Describe the solution you'd like**
Hazen should be released under an open source license as per [NHS Service Standards guidance](https://service-manual.nhs.uk/standards-and-technology/service-standard-points/12-make-new-source-code-open). This enables users to run the software [without being at risk of take-downs, shake-downs, or litigation](https://choosealicense.com/no-permission/), and contributors should be aware their work will be used in this way.

Legal advice may be needed when initially implementing a license give the number of contributors.

**Describe alternatives you've considered**
There are a dizzying number of OSS licenses. I have no strong preferences but would prefer Hazen not to be used in close-source commercial software.

**Additional context**
[Current license file:](https://github.com/GSTT-CSC/hazen/blob/main/LICENSE.txt)
> No license is granted for the use, modification or distribution of this software.

[GitHub advice on 'No license':](https://choosealicense.com/no-permission/)
![image](https://user-images.githubusercontent.com/87647715/161992648-5b0b3442-8732-47de-a804-641562c08473.png)

![image](https://user-images.githubusercontent.com/87647715/161988035-a38f5483-473e-4ba1-9c0e-443d4fdce551.png)
[NHS Service Standard](https://service-manual.nhs.uk/standards-and-technology/service-standard-points/12-make-new-source-code-open)

**Comment by tomaroberts** [comment]
@hshuaib90 – this is quite an important Issue. What licence would you prefer for hazen? Apache 2.0? Other?

**Comment by hshuaib90** [comment]
@tomaroberts agreed, this is very important. We should license this core library as Apache 2.0 immediately. The web app would not be licensed for now.
