### ISSUE TITLE
CLIParser test fail under Windows with relative path names

### ISSUE THREAD

**Issue by pcw24601** [GSTT-CSC/hazen#227]
**Describe the bug**
The CLI parser tests fail when run in a Windows environment.

**To Reproduce**
1. Open PyCharm in a Windows environment.
2. Run `pytest` for `tests`.
3. Tests fail if not run in the correct path.

**Expected behavior**
Tests should pass under both *nix and Windows file systems regardless of starting directory.

**Screenshots**
![image](https://user-images.githubusercontent.com/87647715/162160617-9721159d-4c03-4e0c-93cb-1711fe40f427.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2

**Additional context**
Suggest using TEST_DATA_DIR

**Comment by tomaroberts** [comment]
@pcw24601 – looks like this was resolved in release 0.7.0 a little while back. Are you happy if I close this issue?
