### ISSUE TITLE
Report figure has no labels on x and y axis

### ISSUE THREAD

**Issue by simonshah** [GSTT-CSC/hazen#234]
Please can the plot in the figure show labels on the x- and y- axes .
![image](https://user-images.githubusercontent.com/103638799/163370713-77136d98-8cf7-491b-a6b4-cb63b92bf8cb.png)

Slice position error [mm] (y-axis) as function of slice position [slice number] (x-axis), centred on slice 30

Thanks
Simon

**Comment by tomaroberts** [comment]
@heyhaleema – can this be closed? I see you merged the PR linked above in v1.0.5/1.1.0.

**Comment by heyhaleema** [comment]
Resolved by #279.
