### ISSUE TITLE
Improved code uniformity across tasks

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#250]
**Is your feature request related to a problem? Please describe.**
When developing a web interface for Hazen we have come across multiple issues caused by tasks having variable expected inputs. 

**Describe the solution you'd like**
Refactor the hazen library to use an object oriented approach

**Describe alternatives you've considered**
Modifying the existing  tasks to all accept identical inputs, this approach might be simpler in the short term but the OO approach will make Hazen easier to maintain in the long term.

**Comment by tomaroberts** [comment]
@laurencejackson – is this still applicable given your re-factoring and the `HazenTask` class?

**Comment by laurencejackson** [comment]
Resolved by #266
