### ISSUE TITLE
Test failure: Test512Matrix.test_get_rods - Arrays are not almost equal to 4 decimals

### ISSUE THREAD

**Issue by RFranklin-MR** [GSTT-CSC/hazen#269]
I ran the unit tests after installing hazen (master branch at 1/9/2022) on a Mac. One of the unit tests in test_slice_width.py: Test512Matrix.test_get_rods fails with the following error:

![image](https://user-images.githubusercontent.com/76956172/189377954-ac59c9b0-e597-4485-8552-980346d6c03e.png)

Please let me know if any further information is needed. This test failure doesn't seem serious (the values are equal to 3 decimals).

**Comment by Lucrezia-Cester** [comment]
Hi  @RFranklin-MR, I have investigated this issue and found that the assert_almost_equal has already been changed to 3 decimal places rather than 4, so this issue should not be there. Are you using the latest version?

**Comment by RFranklin-MR** [comment]
This issue was in master on 1st September this year; if it has been changed since that time then this issue can be closed.

**Comment by tomaroberts** [comment]
Thanks for added info Rachael. I've just run `pytest tests/test_slice_width.py` locally and no errors. Will close issue – please raise again if see any more in future.
