### ISSUE TITLE
Spatial_Resolution has 2 functions that are unused

### ISSUE THREAD

**Issue by Lucrezia-Cester** [GSTT-CSC/hazen#284]
Sp_Res task has 2 functions: 

1) get_right_edge_normal_profile

2)create_line_iterator

that are not used. 

This is confusing. 

I would suggest in the Read_The_Docs we include where the reference for this code comes from and a description of what each function is supposed to achieve so that we can keep track of what the code is doing from start to finish. 

After this is documented I think we can safely remove the 2 unused functions.

This should be ideally done for each task. 

@heyhaleema , @tomaroberts , @laurencejackson , @hshuaib90 , let me know if you approve of this solution

**Comment by heyhaleema** [comment]
My two cents are that we should remove functions that aren't being used and/or add them as a `todo` comment (or raise a new issue).

**Comment by Lucrezia-Cester** [comment]
@heyhaleema sounds good. I removed them and opened a PR for it. I'll also add the ISO formula on the PR so we can check what those functions were doing.

**Comment by sophie22** [comment]
would be good to identify the PR mentioned in the comment above. check status of this issue

**Comment by tomaroberts** [comment]
@sophie22 – these have already been removed and merged: https://github.com/GSTT-CSC/hazen/commit/9e8c9b9325f89492944258393e955802a996491f

I'll close the Issue.
