### ISSUE TITLE
Status check applicable to main branch gets stuck on "waiting for status to be reported"

### ISSUE THREAD

**Issue by heyhaleema** [GSTT-CSC/hazen#289]
Recent PRs seem to consistently have 1 expected check pending which never gets reported, i.e. `test`:

![Screenshot 2022-12-16 at 14 12 22](https://user-images.githubusercontent.com/67117138/208134344-6ff71324-7117-4033-9c24-2c3eab704c2f.png)

![Screenshot 2022-12-16 at 14 12 13](https://user-images.githubusercontent.com/67117138/208134354-ab2d9da2-c4a9-4f2b-a0df-20d87cc545ff.png)

This doesn't seem to have a source(?) vs. those in the branch protection rules applicable to `release/*`:

![image](https://user-images.githubusercontent.com/67117138/208134857-aa8cd78f-c521-4396-ba66-d6a6e225549b.png)

The result is we end up bypassing branch protections to merge PRs:

![image](https://user-images.githubusercontent.com/67117138/208414043-ff5c1773-9287-4b30-8130-57666dbe995f.png)

**Comment by tomaroberts** [comment]
I think @laurencejackson said this is a known bug in GitHub?

**Comment by laurencejackson** [comment]
I remember seeing a post somewhere saying that this was a known issue, but now I've had another look around I think its probably related to the `if: github.event.pull_request.base.ref == 'main'` statement at the end of the test job in tests_development.yml. This condition evaluates to true when the branch the PR merges into the main branch. 

It looks like for whatever reason - when this condition is True and the step runs the result is never returned. This could be an issue with the action (schneegans/dynamic-badges-action@v1.3.0). 

I think we should open a new PR to explore this, happy to do this unless someone else is interested?

**Comment by laurencejackson** [comment]
Sorry, @heyhaleema think I understand what you're saying now. You're right we used to have one 'test' job, but now we test on dev and on release. This meant that 'test' was never run so it couldn't get a status. 

I've updated the branch protection rule to use the correctly named tests.
