### ISSUE TITLE
Readme images missing

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#290]
**Describe the bug**
The images showing example hazen outputs are not longer displayed on the readme.

**To Reproduce**
View the readme on github at https://github.com/GSTT-CSC/hazen

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/33687657/208146400-f69b7847-b8a8-43f1-9bed-95f542a1bc03.png

**Additional context**

**Comment by tomaroberts** [comment]
Resolved
