### ISSUE TITLE
Improve docopt CLI interface description

### ISSUE THREAD

**Issue by pcw24601** [GSTT-CSC/hazen#307]
The CLI interface description in the docstring in `./hazenlib/__init.py__ ` does not conform to the `docopt` specification. The `arguments` dict returned by `docopt(__doc__)` contains keys for the tasks (which are not used), in addition to having the task stored under the `<task>` key. Furthermore, it contains an `Options:` key.

The `__doc__` string should be re-written to follow the `docopt` [specifications](https://docopt.readthedocs.io/en/latest/) (see [examples](https://towardsdatascience.com/using-docopt-in-python-the-most-user-friendly-command-line-parsing-library-5c6aeac14deb) and [more examples](https://github.com/docopt/docopt/tree/master/examples)). Including better usage cases would be ideal, especially for options which only apply to one task.

Example:
Calling `hazen relaxometry my/path` creates the following `arguments` dict:
```
{'--calc_t1': False,
 '--calc_t2': False,
 '--help': False,
 '--log': None,
 '--measured_slice_width': None,
 '--output': None,
 '--plate_number': None,
 '--report': False,
 '--show_relax_fits': False,
 '--show_rois': False,
 '--show_template_fit': False,
 '--verbose': False,
 '--version': False,
 '-h': False,
 '<folder>': 'my/path',
 '<task>': 'relaxometry',
 'Options:': False,
 'acr_ghosting': False,
 'acr_uniformity': False,
 'ghosting': False,
 'relaxometry': False,
 'slice_position': False,
 'slice_width': False,
 'snr': False,
 'snr_map': False,
 'spatial_resolution': False,
 'uniformity': False}
```
All entries below `<task>` should not be present.

**Comment by sophie22** [comment]
further information on docopt (and the alternative, argparse) for future reference: https://stackoverflow.com/questions/20599513/python-difference-between-docopt-and-argparse
https://realpython.com/comparing-python-command-line-parsing-libraries-argparse-docopt-click/
