### ISSUE TITLE
Unexpected outputs from ACR modules

### ISSUE THREAD

**Issue by elizaGSTT** [GSTT-CSC/hazen#314]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by YassineAzma** [comment]
You need to put all 11 slices from an ACR series in the same folder. The naming scheme doesn't matter. 

![image](https://user-images.githubusercontent.com/96583432/214590536-ab1eeab6-ab1a-47fd-af50-b5e3e76181fc.png)

At the moment, only axial series are supported. I'll write some documentation at some point once a script exists for each function.

**Comment by elizaGSTT** [comment]
Do you have a specific dataset you tested these functions with? Cause I am trying to test the functions with some of my data and the results do not make massive sense.

**Comment by YassineAzma** [comment]
@elizaGSTT 

Can you send me the data please?

**Comment by YassineAzma** [comment]
@elizaGSTT 

In absence of a reply, I'll close the issue. If there are any future issues, please provide me with more information or send me the data.
