### ISSUE TITLE
CLI parser tests fail in Windows - path error

### ISSUE THREAD

**Issue by pcw24601** [GSTT-CSC/hazen#316]
**Describe the bug**
Some CLI parser tests in `test_hazenlib` fail when run in PyCharm Windows. File paths are passed using a *nix format rather than platform independent format.

**To Reproduce**
1. Run test suite in PyCharm.
2. Tests `TestCliParser.test1_logger` and `TestCliParser.test_relaxometry` in `test_hazenlib.py`  fail with a `FileNotFoundError`.

**Expected behavior**
All tests should pass.

**Screenshots**
```
test_hazenlib.py:165 (TestCliParser.test1_logger)
self = <tests.test_hazenlib.TestCliParser testMethod=test1_logger>

    def test1_logger(self):
        sys.argv = ["hazen", "spatial_resolution", ".\\tests\\data\\resolution\\RESOLUTION\\", "--log", "warning"]
    
        sys.argv = [item.replace("\\", "/") for item in sys.argv]
    
>       hazenlib.main()

test_hazenlib.py:171: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\hazenlib\__init__.py:340: in main
    files = get_dicom_files(arguments['<folder>'])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

folder = './tests/data/resolution/RESOLUTION/', sort = False

    def get_dicom_files(folder: str, sort=False) -> list:
        if sort:
            file_list = [os.path.join(folder, x) for x in os.listdir(folder) if is_dicom_file(os.path.join(folder, x))]
            file_list.sort(key=lambda x: dcmread(x).InstanceNumber)
        else:
>           file_list = [os.path.join(folder, x) for x in os.listdir(folder) if is_dicom_file(os.path.join(folder, x))]
E           FileNotFoundError: [WinError 3] The system cannot find the path specified: './tests/data/resolution/RESOLUTION/'

..\hazenlib\tools.py:148: FileNotFoundError
```
**Desktop (please complete the following information):**
 - Windows 10
 - PyCharm Community Edition 2022.3.1

**Comment by sophie22** [comment]
Tested on a Windows 10, freshly installed Python 3.9.7 with a new virtual environment, all tests passed on my machine.
================= 219 passed, 371 warnings in 155.45s (0:02:35) =================

Version of hazenlib tested is the `main` at the time of testing, from this commit: https://github.com/GSTT-CSC/hazen/commit/a8ce43984a72c6b4f11cbca6a60bafbe32234695

@pcw24601 Please check if the issue still occurs with the latest release of hazen, I was unable to recreate the issue.

**Comment by tomaroberts** [comment]
Closing – Paul, if this arises again, please re-open the Issue or raise a new one. Thanks.

**Comment by pcw24601** [comment]
I've tested this on my Windows machine and it's passing the test suite.

FYI: I'm no longer working in medical physics or undertaking MRI QA. I'm still interested in the area, but it might take me a while to reply. Best wishes with the future of the Hazen, it's a great, well-needed project.

**Comment by tomaroberts** [comment]
Thanks for all your contributions @pcw24601 – good luck with your future endeavours!
