### ISSUE TITLE
acr geometric accuracy module 

### ISSUE THREAD

**Issue by elizaGSTT** [GSTT-CSC/hazen#332]
as seen in the screenshot there is bad centering and results are therefore far off. @YassineAzma 

<img width="617" alt="Screenshot 2023-04-06 at 10 45 02" src="https://user-images.githubusercontent.com/93722461/231781745-3edd17b4-4ef2-4d64-bf74-caf00b52328b.png">

**Comment by YassineAzma** [comment]
Resolved in #343.

Please don't acquire with just the spine coil.
