### ISSUE TITLE
acr ghosting module

### ISSUE THREAD

**Issue by elizaGSTT** [GSTT-CSC/hazen#333]
problem centering ROIs. this datset is from bodycoil acquisition. @YassineAzma 
<img width="592" alt="Screenshot 2023-04-06 at 10 40 41" src="https://user-images.githubusercontent.com/93722461/231783117-9cce4c18-0783-4593-9596-5d989c6b728e.png">

**Comment by tomaroberts** [comment]
hazen Backlog – @elizaGSTT said this has only occurred once, so might not be ongoing issue.
