### ISSUE TITLE
QMS Conformity 

### ISSUE THREAD

**Issue by elizaGSTT** [GSTT-CSC/hazen#334]
requirement to print the expected results and obtained result for each new hazen version to ensure we comply with ISO9001.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/93722461/231783552-4b3213ab-1527-4bc7-beea-72348e418577.png">
<img width="554" alt="image" src="https://user-images.githubusercontent.com/93722461/231783781-2563d090-1950-4f9e-aaa4-541f33d2666d.png">
<img width="555" alt="image" src="https://user-images.githubusercontent.com/93722461/231783944-ca4f809c-766c-44b9-81f4-8e80b073b3cc.png">

**Comment by Lucrezia-Cester** [comment]
thank you @elizaGSTT for adding it all here. 

I will start implementing today's proposed solution:

the pytest tests/ script should print in the CLI the expected results and the outputted results of the tests scripts.

**Comment by Lucrezia-Cester** [comment]
@elizaGSTT, i have solved the issue in this PR https://github.com/GSTT-CSC/hazen/pull/335. 

The resolution is as follows:

when you run pytest -v -s tests/ you will be able to see the output of the hazenlib funcitons in the terminal compared to a set of fixed values taken from test images in a test folder.
