### ISSUE TITLE
Could the data for ACR tests be relabelled?

### ISSUE THREAD

**Issue by Lucrezia-Cester** [GSTT-CSC/hazen#341]
Currently the data in the acr test folder does not follow conventional labelling convention. Could this be relabelled:

ex: SiemensMTF to spatial_resolution_acr_test

**Comment by tomaroberts** [comment]
hazen Backlog – Yassine going to tackle

**Comment by YassineAzma** [comment]
I can't seem to see any coherent naming convention in the existing folders.

Here are some examples:

tests > data > ghosting > GHOSTING
tests > data > ghosting > PE_COL_PHANTOM_BOTTOM_RIGHT
tests > data > resolution > eastkent 
tests > data > resolution > philips 
tests > data > resolution > RESOLUTION
tests > data > snr > VIDA

Why are some of these site-specific and others simply have the name of the test repeated in caps? The one that looks the most sensible to me is the convention in:

tests > data > snr > GE
tests > data > snr > Philips
tests > data > snr > Siemens

I don't think another folder saying the test name in caps or the site is very useful. I think the directory should state what is unique about the dataset, i.e. the manufacturer first and then how it varies from any other datasets from that manufacturer.

Before I commit to any changes, how does this setup sound to you for the ACR data?  @tomaroberts 

parent directory: tests > data > acr

1) GE
2) Siemens > general (directory contains 11 images of typical ACR data)
3) Siemens > general_noise (the previous dataset with added noise for the subtraction SNR test)
4) Siemens > spatial_resolution (directory contains 11 images of typical ACR data at a slant for MTF)

**Comment by tomaroberts** [comment]
@YassineAzma – Thanks for highlighting the test data naming inconsistencies. I agree, it's something we should revise and make consistent.

You're suggested data structure for `tests/data/acr` looks logical to me. Go ahead, thanks.

**Comment by sophie22** [comment]
ACR test data is organised in a logical way, considering this issue resolved.
