### ISSUE TITLE
Manufacturer not supported (Esaote) 

### ISSUE THREAD

**Issue by ElizabethGabriel** [GSTT-CSC/hazen#345]
Esaote manufacturer not supported (scanner now under a GSTT QA contract). 
Issues with multiple tests using ACR phantom (inc SNR, geometric accuracy using wrong slices etc..). 
Test Esaote dataset available on GSTT Sharepoint (file too large to add as attachment) and can be emailed over if needed. 
Issue reported on behalf of Rebecca Thornley and David Price

**Comment by YassineAzma** [comment]
Hi, @ElizabethGabriel . Can you please email the dataset to yassine.azma@rmh.nhs.uk

Thanks.

**Comment by tomaroberts** [comment]
Asked Yassine at hazen Backlog today – he is working on it

**Comment by sophie22** [comment]
Hi @ElizabethGabriel would you be able to share the dataset that is causing the error with me too please?
My GSTT email address is for sophie.ratkai
