### ISSUE TITLE
Improve displaying results on terminal

### ISSUE THREAD

**Issue by sophie22** [GSTT-CSC/hazen#355]
PrettyPrinter could be replaced with `json.dumps()` that can format and display the result dictionary in a simple structured way with less configuration needed.

currently with PrettyPrint: (more compact)
<img width="759" alt="Screenshot 2023-07-15 at 18 27 16" src="https://github.com/GSTT-CSC/hazen/assets/15593138/f22dad3d-c0b2-4b41-88b1-1a48d52758cf">

with json.dumps: (more easy to understand)
<img width="686" alt="image" src="https://github.com/GSTT-CSC/hazen/assets/15593138/63af6d46-fddc-4acc-84fc-da5a92c936f5">

**Comment by sophie22** [comment]
removing the added nesting of "IPEM" makes it even prettier:
<img width="677" alt="image" src="https://github.com/GSTT-CSC/hazen/assets/15593138/831c8c07-ef7e-45b6-9c9f-be9ee9fdaf64">

**Comment by tomaroberts** [comment]
That looks clearer to me. We should ask the users for their preference.

Is there a benefit to switching from PrettyPrinter to json.dumps ?

**Comment by tomaroberts** [comment]
@elizaGSTT

See above. Would it be an issue for you if we altered the formatting of the command line outputs? Like Sophie's screenshots above show?

In our view, it's cleaner so easier to interpret the results. And, it will potentially help us with the web app too.

But, if the formatting is important for your workflow, let us know.

**Comment by elizaGSTT** [comment]
i agree the IPEM text doesn't add anything and it does look cleaner and easier to read without it.

**Comment by tomaroberts** [comment]
@elizaGSTT – so happy if we go ahead with these changes then? It's not going to affect how you process the results into your Excel and PDF report?

**Comment by elizaGSTT** [comment]
we currently just copy those values into an excel spreadsheet so it shouldn't affect anything on this part. I believe it's okay to move on with this change as we know that these values are all calculated using the methods outlined by the IPEM report anyway.

**Comment by tomaroberts** [comment]
@sophie22 – would you like to create a PR with your improvements for this Issue?

**Comment by sophie22** [comment]
yes, will have to merge in main first. but will create a PR later today!
