### ISSUE TITLE
Report images for relaxometry task

### ISSUE THREAD

**Issue by sophie22** [GSTT-CSC/hazen#360]
Currently the relaxometry task is not yet refactored to inherit from the HazenTask class and it's figures and diagrams generated with the `--show_rois`, `--show_template_fit` and `--show_relax_fits` options are not available. Currently matplotlib is not configured to be able to make pop out windows to show these diagrams and it's not implemented to save these figures.

I propose to refactor the report generation part of the relaxometry task to follow the procedure of other tasks and save the figures to file with the `--report` option, replacing the current the individual options.

**Comment by tomaroberts** [comment]
Resolved by #361
