### ISSUE TITLE
ACR SNR results 

### ISSUE THREAD

**Issue by elizaGSTT** [GSTT-CSC/hazen#368]
@YassineAzma  i think the values are not correctly displayed. the comma should be after the 4th not the 5th digit.

<img width="957" alt="image" src="https://github.com/GSTT-CSC/hazen/assets/93722461/27ac1e41-b076-446c-8b46-30ab697e73d2">

**Comment by YassineAzma** [comment]
@elizaGSTT 

There is no string formatting applied to the output, so what you get there is just the measured SNR multiplied by a normalisation factor. The code for the normalisation factor is identical to that of the MagNet SNR function.

Could you please tell me the following parameters for the scan?

In-plane resolution
Bandwidth
TR
Matrix size (rows & columns)
Slice thickness

Alternatively, you can send me a screenshot of the DICOM metadata.

**Comment by elizaGSTT** [comment]
Is it easier if I give you the images maybe?

**Comment by YassineAzma** [comment]
@elizaGSTT That works too.

**Comment by elizaGSTT** [comment]
From: Yassine Azma ***@***.***>
Date: Wednesday, 2 August 2023 at 15:18
To: GSTT-CSC/hazen ***@***.***>
Cc: Stamou Elizabeth ***@***.***>, Mention ***@***.***>
Subject: Re: [GSTT-CSC/hazen] ACR SNR results (Issue #368)

@elizaGSTT<https://scanmail.trustwave.com/?c=8248&d=vuXK5DIbjzEw-xEDmh8JH_qb6eM1co8t5vyuM5mjxA&u=https%3a%2f%2fgithub%2ecom%2felizaGSTT> That works too.

**Comment by tomaroberts** [comment]
Hi both – what is the latest with this one? I'm slightly unclear if this is just a formatting issue or something more?

Just wanted to add that with the latest release we implemented an adjustment to the way the CLI outputs the results. It should hopefully be clearer to read. Might be worth checking again to see if this is still an issue.

**Comment by YassineAzma** [comment]
It's not a formatting issue. My suspicion is either the centre of the phantom has been located incorrectly or there are very strange acquisition parameters. I won't know until I receive more information, whether that is the DICOM metadata, the images, or the report.

**Comment by tomaroberts** [comment]
@elizaGSTT – can you provide Yassine with the added info he needs please? Thanks.

**Comment by elizaGSTT** [comment]
here's the dataset: 
[DISTOFF_NORMOFF.zip](https://github.com/GSTT-CSC/hazen/files/12596667/DISTOFF_NORMOFF.zip)

**Comment by YassineAzma** [comment]
@elizaGSTT 
The normalisation factor is calculated correctly and the function for doing this is identical to that in the snr function for the MagNet phantom. If you have a reference for the normalisation factor, could you please share it? I have no idea where the formula comes from. 

Here's me verifying in Excel.
![image](https://github.com/GSTT-CSC/hazen/assets/96583432/70c39f96-7353-40da-b601-fe01baca096d)

Hazen indicates that the protocol you used has the following:

dx/dy/dz = 0.5mm/0.5mm/5mm
BW = 130Hz
TR = 500ms
Rows = 512
Cols = 512
Averages = 1

Can you please confirm?

Is there a particular reason that the in-plane resolution is 0.5 by 0.5? Do you have interpolation/zero-fill on? When I look at the DICOM meta-data in DicomBrowser, the acquisition matrix is 256x256, which contradicts the metadata being read by Hazen looking at rows and columns as you can see above. All of this makes me think you have interpolation/zero-fill on.

![image](https://github.com/GSTT-CSC/hazen/assets/96583432/4ea96661-ea87-4951-9981-c82532e0ed1d)

Changing the rows and columns to 256x256 gives a normalised SNR of 5510.467, which is much more reasonable. Please confirm that the protocol did not have interpolation/zero-fill on.

**Comment by sophie22** [comment]
@elizaGSTT could you please provide on update on what's the latest with this issue and whether you require us to do further investigations/code fixes?

**Comment by sophie22** [comment]
Closing this issue as it appears to stem from data acquisition rather than bugs in the code. Feel free to reopen if the issue is encountered again.
