### ISSUE TITLE
Requests from physicists

### ISSUE THREAD

**Issue by sophie22** [GSTT-CSC/hazen#376]
I had an amazing and informative session with Elizabeth, Becky and the physics team on 13/09/23, going through the end-to-end process of acceptance testing and quality assurance, that includes the use of hazen.
We discussed data acquisition: file naming and structuring standards, what additional information could be parsed from the DICOM  headers that may be useful during analysis; task-specific issues and requests and how hazen output is adapted for the final reports. Below are a few of the issues that I think are worth to implement as improvements to the current tool.

1. Rename the `slice_width` task of the MagNet phantom to `geometric_accuracy` to align with the ACR phantom task name, and because this task calculates linearity and distortion in addition to slice width.
2. ~~Might merge the `ACR geometric accuracy` and `slice thickness` tasks for the above reasons.~~
3. Double check the implementation of the formulae used for every task.
4. Calculate and return only the maximum and average in the `slice_position` task.
5. Display units in the key describing each value in the result.
6. SNR task:
    - set default kernel size to 9
    - in order to simplify folder structure in preparation for hazen, use DICOM field values to pair up images for SNR by subtraction
    - parse coil type (head/body) from DICOM tag if available, have manual flag to override
    - parse orientation from DICOM tag if possible, otherwise parse from SeriesDecription - relies on user correctly naming it
    - decision to be made whether SNR to be calculated by subtraction or smoothing for ACR images (subtraction requires acquisition of a second set)
7. Potentially 'merge' ACR tasks so that they are run with a single command as they all take the same set of input files.
    --> create 'task sets' that include multiple ACR tasks, but not all - waiting for physicists to confirm which ones relate
9. Spatial resolution check for and use appropriate matrix size 256/512 in both tasks.

**Comment by sophie22** [comment]
Outcome of the hazen weekly discussion with @tomaroberts on 14 Sep.

1. and 2. are not priority, need further discussion with MR physics team. There is a separate discussion ongoing around improving the `ACR geometric accuracy` task in #378 
3. low priority, potentially ask a physics trainee to check
4. simplified `slice_position` result is implemented in #375 🎉 
5. providing units and appropriate rounding is mostly implemented in #375 pending review
6. SNR task default kernel is currently set to 9 ✔️ 
    * automatic pairing of images for SNR task is handled in #379
    * it is preferred to use the SNR by subtraction values, but they should be comparable with SNR by smoothing.
7. ACR "super" task is handled in #380
8. Spatial resolution investigation of matrix size requires further investigation

**Comment by elizaGSTT** [comment]
> I had an amazing and informative session with Elizabeth, Becky and the physics team on 13/09/23, going through the end-to-end process of acceptance testing and quality assurance, that includes the use of hazen. We discussed data acquisition: file naming and structuring standards, what additional information could be parsed from the DICOM headers that may be useful during analysis; task-specific issues and requests and how hazen output is adapted for the final reports. Below are a few of the issues that I think are worth to implement as improvements to the current tool.
> 
> 1. Rename the `slice_width` task of the MagNet phantom to `geometric_accuracy` to align with the ACR phantom task name, and because this task calculates linearity and distortion in addition to slice width.
> 2. Might merge the `ACR geometric accuracy` and `slice thickness` tasks for the above reasons.
> 3. Double check the implementation of the formulae used for every task.
> 4. Calculate and return only the maximum and average in the `slice_position` task.
> 5. Display units in the key describing each value in the result.
> 6. SNR task:
>    
>    * set default kernel size to 9
>    * in order to simplify folder structure in preparation for hazen, use DICOM field values to pair up images for SNR by subtraction
>    * parse coil type (head/body) from DICOM tag if available, have manual flag to override
>    * parse orientation from DICOM tag if possible, otherwise parse from SeriesDecription - relies on user correctly naming it
>    * decision to be made whether SNR to be calculated by subtraction or smoothing for ACR images (subtraction requires acquisition of a second set)
> 7. Potentially 'merge' ACR tasks so that they are run with a single command as they all take the same set of input files.
> 8. Spatial resolution check for and use appropriate matrix size 256/512 in both tasks.


@sophie22 thank you so much for putting this together! i just have a couple of comments. on point 2, i'm not sure what you mean by merging these two but for the ACR the geometric accuracy and slice thickness are two separate tests and that should be clear when displaying the results. i would suggest not merging them under a single module. 
also for the ACR again, on point 7 merging all tasks sounds good however it's a bit trickier and on our part might not be tremendously useful cause as we said we acquire two datasets with different filters and use these for different tests. so maybe keep that on the side for a bit and we could potentially find another way to optimize the ACR tests later on. 
Hope that makes sense. i'm happy with the other points.

**Comment by sophie22** [comment]
Thank you for the feedback, 2 is discarded and 7 is marked low priority for now. Instead, I will be focusing on enabling hazen to handle enhanced DICOMs in the near future.

**Comment by sophie22** [comment]
Comments/features raised in this issue have been resolved or deprioritised. Closing thread for now, discussions can continue on the separately raised issues
