### ISSUE TITLE
Incompatible python versions

### ISSUE THREAD

**Issue by RebeccaThornley** [GSTT-CSC/hazen#412]
**Description**
A few members of our team have freshly downloaded hazen recently using versions of python higher than 3.9. Using the pip install with these later versions of python results in an old version of hazen being downloaded (1.0.2). Both 3.11 and 3.12 have been tested. 

**To Reproduce**
Following pip install guidance:

python3 -m venv hazen-venv [or python3.11(12) -m venv hazen-venv]
source hazen-venv/bin/activate
pip install hazen

**Expected behavior**
Currently instructions say that python version of 3.9 or higher is required. Therefore expected v3.11 or v.12 to be compatible. 

**Screenshots**
<img width="575" alt="Screenshot 2024-02-15 at 09 50 22" src="https://github.com/GSTT-CSC/hazen/assets/125027684/4ab59ecf-89d4-4301-b6cb-6bf0e2773a20">

**Desktop:**
 - OS: macOS SOnoma v14.2.1
 - Python version: 3.12
 - Hazen version: results in download of 1.0.2
 - Deployment: venv

**Additional context**
This isn't a big problem as the easy work around is to download python3.9 and install hazen with this. But if it is the case that 3.9 is a requirement could the instructions be updated to be more clear?

**Comment by sophie22** [comment]
I managed to install the latest hazen version (v1.3.2) after modifying the pypi config file which had a requirement for Python version to be below 3.11. This manually installed version produced results for all MagNet and ACR datasets and tasks in my test folders, so I don't see why this Python version restriction was hard coded.

Will ask around in the development team and if there are no objections, I will update the Python version requirement to be above 3.9, which should support latest Python versions. I envision this to become available in the next release, planned for sometime in May.
