### ISSUE TITLE
[HZN-51] Prevent ghosting from returning negative values

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#51]
Transferred by @LaurenceJackson on Aug 9, 2020, 18:23

:::Issue recreated from Jira issue [HZN-51](https://gsttmri.atlassian.net/browse/HZN-51):::

*strong text*Imported from https://bitbucket.org/gsttmri/hazen/issues/52/prevent-ghosting-from-returning-negative

**Comment by laurencejackson** [comment]
Transferred by @LaurenceJackson on Sep 4, 2020, 17:00

[Comment originally posted by Elizabeth.gabriel 2020-09-04T16:00:54.598+0100

Further to this, the ghosting reports have been displaying ROI boxes in the incorrect locations, for example BMI Mile End. Investigate whether this is a coordinate switching issue. 

!image-20200904-145736.png|width=1044,height=926!

 (data here [https://emckclac-my.sharepoint.com/:f:/r/personal/stra9543_kcl_ac_uk/Documents/shared_physics-mri/quality/qa/BMI Sites/BMI_Mile_End_15T_Siemens_Avanto/SiteVisitSept2020/mile_end_data?csf=1&web=1&e=VwWsJ5|https://emckclac-my.sharepoint.com/:f:/r/personal/stra9543_kcl_ac_uk/Documents/shared_physics-mri/quality/qa/BMI%20Sites/BMI_Mile_End_15T_Siemens_Avanto/SiteVisitSept2020/mile_end_data?csf=1&web=1&e=VwWsJ5] )]

**Comment by laurencejackson** [comment]
Transferred by @LaurenceJackson on Sep 22, 2020, 19:01

[Comment originally posted by Elizabeth.gabriel 2020-09-22T18:01:16.288+0100

!image-20200911-141656.png|width=642,height=532!

When corrected location of ghost ROI, can see edges are extending beyond specified region to look for ghosting. ]

**Comment by laurencejackson** [comment]
Transferred by @LaurenceJackson on Sep 25, 2020, 12:08

[Comment originally posted by Haris Shuaib 2020-09-25T11:08:25.592+0100

The box technically defines the limit of the central pixel of the ROI, i don't think that's a major issue]

**Comment by laurencejackson** [comment]
Transferred by @LaurenceJackson on Sep 4, 2020, 17:00

![image-20200904-145736](https://my-gitlab-bucket.s3.amazonaws.com/393326940/9d8d2eea20c7a934299c55fcb342cfb0.png)

**Comment by laurencejackson** [comment]
Transferred by @LaurenceJackson on Sep 22, 2020, 19:01

![image-20200911-141656](https://my-gitlab-bucket.s3.amazonaws.com/393326940/4147063110d23bc6823be5fd1a992761.png)

**Comment by hshuaib90** [comment]
related to #109 - possibly solved by ghosting ROI in phase direction.

**Comment by tomaroberts** [comment]
Resolved by #185
