### ISSUE TITLE
[HZN-58] SNR-get phantom shape from automatic thresholding rather than shape fitting

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#58]
Transferred by @LaurenceJackson on Aug 9, 2020, 18:23

:::Issue recreated from Jira issue [HZN-58](https://gsttmri.atlassian.net/browse/HZN-58):::

Imported from https://bitbucket.org/gsttmri/hazen/issues/59/snr-get-phantom-shape-from-automatic  SNR routine fails if it is unable to fit a circle \(axial\) or rectangle \(sagittal or coronal\) to the image.In addition to failing if the shape fitting algorithm fails, it also assumes a cylindrical phantom and non-oblique acquisition.Using an automatic thresholding algorithm, such as skimage.filters.threshold\_li could avoid this problem and simultaneously remove the restrictions on phantom shape and acquisition plane.Preliminary investigation shows threshold\_li, threshold\_minimum and thershold\_triangle may give acceptable results, but threshold\_iosdata, threshold\_mean, threshold\_yen and threshold\_otsu are unlikely to work.Automatic thresholding should be applied to the smoothed image to reduce the effect of noise.

**Comment by hshuaib90** [comment]
related to #108

**Comment by tomaroberts** [comment]
#137 resolves this issue.
