### ISSUE TITLE
[HZN-61] SNR-allow custom structuring element morphology and size

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#61]
Transferred by @LaurenceJackson on Aug 9, 2020, 18:23

:::Issue recreated from Jira issue [HZN-61](https://gsttmri.atlassian.net/browse/HZN-61):::

Imported from https://bitbucket.org/gsttmri/hazen/issues/62/snr-allow-custom-structuring-element  The structuring element shape \(boxcar\) and size \(3x3\) are hard-coded in snr.smoothed\_subtracted\_image. It would be useful to enable a custom structuring element shape and size.E.g.`from scipy import ndimage`  `from skimage import filters, morphology``smoothing_kernel = morphology.square(kernel_len) # Boxcar kernel`  `smoothing_kernel = smoothing_kernel / smoothing_kernel.sum()`  `smooth_image = ndimage.filters.convolve(original_image, smoothing_kernel)`‌

**Comment by laurencejackson** [comment]
Stale issue, closing for now. Please comment if further work is required.

@pcw24601, you raised the original, is this still required?

**Comment by pcw24601** [comment]
It would be a nice enhancement but I'm happy for it to be closed.
