### ISSUE TITLE
[HZN-69] SpRes-Get_edge_profile_coords (L341) returns rotated y-coords but original x-coords

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#69]
Transferred by @LaurenceJackson on Aug 9, 2020, 18:23

:::Issue recreated from Jira issue [HZN-69](https://gsttmri.atlassian.net/browse/HZN-69):::

Imported from https://bitbucket.org/gsttmri/hazen/issues/70/spres-get_edge_profile_coords-l341-returns  `Get_edge_profile_coords` \(L341\) returns the rotated y-coords but the original x-coords. The x-coords aren't currently used, and I think all the rotates x-coords would be the same, but it's a bit counter intuitive.

**Comment by tomaroberts** [comment]
Issue resolved - see linked comment above from Haris.
