### ISSUE TITLE
[HZN-70] SpRes-Get_edge_profile_coords (L351) I think spaces the y-coordinates by the x-spacing value

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#70]
Transferred by @LaurenceJackson on Aug 9, 2020, 18:23

:::Issue recreated from Jira issue [HZN-70](https://gsttmri.atlassian.net/browse/HZN-70):::

Imported from https://bitbucket.org/gsttmri/hazen/issues/71/spres-get_edge_profile_coords-l351-i-think  `get_edge_profile_coords` \(L351\) spaces the y-coordinates by the x-spacing value \(I think\). As the pixels are usually square this is unlikely to cause an error, but could be corrected.‌

**Comment by hshuaib90** [comment]
Closed by #140
