### ISSUE TITLE
[HZN-78] Add landing page

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#78]
Transferred by @LaurenceJackson on Aug 12, 2020, 22:36

:::Issue recreated from Jira issue [HZN-78](https://gsttmri.atlassian.net/browse/HZN-78):::

There is no landing page when visiting hazen.herokuapp.com, instead it redirects to the login page. 

The landing page should at least highlight what hazen is and who made it and what you can do.

Currently, we do not want random people using the web app and so a notice indicating that the service is not open for use yet.

It would be good to add a registration link for people to be notified when it's available for use

**Comment by tomaroberts** [comment]
hazen-web-app issue + we have since created a landing page
