### ISSUE TITLE
[HZN-80] Add logging to screen

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#80]
Transferred by @LaurenceJackson on Aug 13, 2020, 11:31

:::Issue recreated from Jira issue [HZN-80](https://gsttmri.atlassian.net/browse/HZN-80):::

Add python logger to print to screen log messages.

Add CLI for setting verbosity (e.g. info, debug, warn, error)

**Comment by hshuaib90** [comment]
Closed with #123
