### ISSUE TITLE
[HZN-85] test_model.py: add test for password reset token function

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#85]
Transferred by @LaurenceJackson on Aug 19, 2020, 16:20

:::Issue recreated from Jira issue [HZN-85](https://gsttmri.atlassian.net/browse/HZN-85):::

add tests for 'password resent token' functions used in models.py to test_model.py.

**Comment by tomaroberts** [comment]
Closing as 3 years old and not relevant to hazen (old web-app issue)
