### ISSUE TITLE
[HZN-9] Geometric Distortion Test - horizontal and vertical distortion values inconsistent with manual method

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#9]
Transferred by @LaurenceJackson on Aug 9, 2020, 18:23

:::Issue recreated from Jira issue [HZN-9](https://gsttmri.atlassian.net/browse/HZN-9):::

Imported from https://bitbucket.org/gsttmri/hazen/issues/10/geometric-distortion-test-horizontal-and  Hi Haris, It’s been noted that the horizontal and vertical distortion values produced by hazen don’t match up well with the manual method. This has been noted for all 6 centres we have investigated. See summary of hazen testing sheet for more info: [https://emckclac-my.sharepoint.com/:x:/g/personal/k1801989\_kcl\_ac\_uk/EQzmzId0RehLuUkZhPe2mXoBtwMO7bfkvFWP519k\_Xnblg?e=nEG2CF](https://emckclac-my.sharepoint.com/:x:/g/personal/k1801989_kcl_ac_uk/EQzmzId0RehLuUkZhPe2mXoBtwMO7bfkvFWP519k_Xnblg?e=nEG2CF) Cheers, Liz‌

**Comment by hshuaib90** [comment]
Possible duplicate of #110

**Comment by tomaroberts** [comment]
Have started getting a handle on this one. Test data in: `Hazen_Issues/CCL_Siemens_Vida/CCL_Geometric_Distortion`

hazen automatically finds the rods in the phantom (marked 1-9 below):

![image](https://user-images.githubusercontent.com/15610752/144890143-80e46e22-838f-4dbc-9862-ff787ab99d23.png)

This is not quite precise enough to fall within the acceptable tolerance of the MR QA reports. For example:

![image](https://user-images.githubusercontent.com/15610752/144889654-263c95d3-61e9-4864-b510-8191990a4ea8.png)

In this case, manual measurement falls within the tolerances, but the hazen-derived geometric distortion value is >0.6%, which is out of tolerance.

I think the centroids of the rods are not being found with enough accuracy. For example, in the image above, the middle-left (no. 4) rod looks slightly off centre.

TODO: investigate rod finding algorithm.

**Comment by laurencejackson** [comment]
Sounds good, could we also add a simple marker (e.g. .'s or x's) and spatially offset the number label - it's pretty hard to see where the centre is from the current annotation.

**Comment by tomaroberts** [comment]
I think this image helps to illustrate why the hazen horiz/vertical linearity measurements are inaccurate compared to manual methods in ImageJ etc:

![image](https://user-images.githubusercontent.com/15610752/145831849-dfd83bbf-8ba9-42b2-ad87-afd3835a85ad.png)

The small coloured blobs are what `scipy.ndimage.label` determines as the rods.
The red dots are the x-y coordinates for each blob according to `scipy.ndimage.measurements.center_of_mass`.

My feeling is that the blobs are weird shapes (ie: not circular) and this is throwing off the centre of mass measurements, for example, in the top-right and middle right-rods the coordinates are right against the edge of the rod. If you were labelling those manually, you'd have much more centralised coordinates.

**Comment by tomaroberts** [comment]
Closed by #175
