### ISSUE TITLE
[HZN-90] Hazenlib: improve __init__.py coverage

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#90]
Transferred by @LaurenceJackson on Aug 21, 2020, 11:58

:::Issue recreated from Jira issue [HZN-90](https://gsttmri.atlassian.net/browse/HZN-90):::

**Comment by Lucrezia-Cester** [comment]
@laurencejackson . Does this mean, expand init.py test coverage?

**Comment by laurencejackson** [comment]
The original reporter was @hshuaib90, but yes I think this means test coverage

**Comment by hshuaib90** [comment]
Yes!

**Comment by Lucrezia-Cester** [comment]
@laurencejackson @hshuaib90 thanks!

**Comment by tomaroberts** [comment]
Resolved by #144
