### ISSUE TITLE
[HZN-93] Add documentation of how to accurately index arrays using OpenCV outputs

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#93]
Transferred by @LaurenceJackson on Aug 27, 2020, 16:28

:::Issue recreated from Jira issue [HZN-93](https://gsttmri.atlassian.net/browse/HZN-93):::

OpenCV methods return locations as (x, y) however array indices are row-major (y, x) and therefore moving between these two reference frames needs to be done with care. 

Documentation needs to be added to the guides section about working with axes and coordinates to help developers and reviewers .

**Comment by laurencejackson** [comment]
Transferred by @LaurenceJackson on Sep 3, 2020, 10:40

[Comment originally posted by Jane.ansell 2020-09-03T09:40:07.624+0100

Do we also need a quick review of all the existing code to check there aren’t any errors (even if they are not causing major problems at the moment?)]

**Comment by laurencejackson** [comment]
Transferred by @LaurenceJackson on Sep 25, 2020, 12:08

[Comment originally posted by Haris Shuaib 2020-09-25T11:08:40.868+0100

Sorry I missed this, yes]

**Comment by laurencejackson** [comment]
Transferred by @LaurenceJackson on Nov 3, 2020, 11:00

[Comment originally posted by Jane.ansell 2020-11-03T10:00:23.574+0000

SOrry, now I missed this\! Shall I make a ticket for reviewing existing code then?]

**Comment by laurencejackson** [comment]
Transferred by @LaurenceJackson on Nov 3, 2020, 11:15

[Comment originally posted by Jane.ansell 2020-11-03T10:15:47.855+0000

Just so we have a record: there is draft documentation proposed for this ticket, uploaded to the Teams hazen chat. ]

**Comment by tomaroberts** [comment]
Closing as 3 years old.
