### ISSUE TITLE
[HZN-94] SNR task: choice of kernel size for different coils

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#94]
Transferred by @LaurenceJackson on Oct 14, 2020, 17:19

:::Issue recreated from Jira issue [HZN-94](https://gsttmri.atlassian.net/browse/HZN-94):::

The McCann 2013 paper which our SNR method and the MATLAB method implements recommends a larger 25x25 smoothing kernel for processing images acquired from the body coil. Currently the kernel is fixed at 9x9.

**Comment by sophie22** [comment]
I think it has been updated and now fixed at the larger 25x25 size, see https://github.com/GSTT-CSC/hazen/blob/main/hazenlib/tasks/snr.py#L127

- if both are required and should be changed dynamically, I suggest we move this value to the params file and make it possible to be overriden from the command line.

**Comment by tomaroberts** [comment]
Hi Sophie - I noticed this myself too on Friday. I'm going to raise with the Physics team.

**Comment by sophie22** [comment]
Response from Physics Team @RFranklin-MR

I’ve reviewed the referenced paper in the issue (https://iopscience.iop.org/article/10.1088/0031-9155/58/11/3775) – and note the following:
“Comparison of the smoothed image subtraction method with the double-image TIC method for various kernel sizes (figure [8](https://iopscience.iop.org/article/10.1088/0031-9155/58/11/3775#pmb451246f8)) confirms that 25 pixels is optimum for body coils, while quadrature and eight-channel head coils require a kernel size of <10 pixels. However, the magnitude of the difference in measured SNR remains small for all coils over a wide range of kernel sizes. **Use of a coil-specific kernel size was found to have no significant advantage over use of a single optimum kernel size of nine pixels**.”
 
I’m not sure where the original issue/request came from – as it’s one copied from jira, so difficult to determine the original intention. However, based on the paper we are following, my preference would be either:
3) Permit user to specify kernel size – if this is preferred, what would you like the default kernel size to be? 9x9 or 25x25? (default 9x9)
Or 
2) Revert kernel to 9x9

**Comment by sophie22** [comment]
Outcome: 
revert default kernel size to 9, make optional CLI argument for body coil to change kernel size to 25

"25 pixels is optimum for body coils, while quadrature and eight-channel head coils require a kernel size of <10 pixels"

**Comment by tomaroberts** [comment]
For 1.3.0 release, we've implemented quick revert to 9x9. Will add kernel option flag in future release.

**Comment by sophie22** [comment]
resolved by #388 Thanks @mollybuckley
