### ISSUE TITLE
[HZN-98] CLI-replace docopt

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#98]
Transferred by @LaurenceJackson on Feb 4, 2021, 24:10

:::Issue recreated from Jira issue [HZN-98](https://gsttmri.atlassian.net/browse/HZN-98):::

The command line interface with docopt is getting very convoluted and requires a redesign. This shouldn't break any of the APIs created with the processors

**Comment by Lucrezia-Cester** [comment]
@laurencejackson what kind of redesign? As it stands right there are a lot of optional arguments so it works just by specifying the task and folder.

**Comment by sophie22** [comment]
Usage instructions for the available commands and options have been reorganised and standardised.
Considering this issue resolved since v1.3.0 #359
