### ISSUE TITLE
[HZN-99] Hazen produced ghosting values do not match ImageJ values

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#99]
Transferred by @LaurenceJackson on Feb 24, 2021, 16:31

:::Issue recreated from Jira issue [HZN-99](https://gsttmri.atlassian.net/browse/HZN-99):::

Hazen ghosting was used to analyse images from ECH Vida acceptance testing.  

The values produced by hazen did not match those produced with ImageJ, and did not match the visible ghosting seen on the images. Values produced either underestimated ghosting or over estimated (for TE=120ms, NSA=1). 

Hazen produced values and ghosting attached below.

**Comment by laurencejackson** [comment]
Transferred by @LaurenceJackson on Feb 24, 2021, 16:27
![image](https://user-images.githubusercontent.com/33687657/143859975-4aa486fc-b38d-4714-b17a-b2a4b4a660b9.png)

**Comment by laurencejackson** [comment]
Transferred by @LaurenceJackson on Feb 24, 2021, 16:29

![image](https://user-images.githubusercontent.com/33687657/143860085-63bcc16a-7f72-4b68-878a-bf951787a57e.png)

**Comment by tomaroberts** [comment]
@laurencejackson 

Can you possibly re-upload the screenshots you posted on 6 Aug – links appear to be broken.

**Comment by tomaroberts** [comment]
Fixed by PR #185
